---
Name: atedo
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\Admin\LeftAndMain:
  application_name: 'atedo CMS'
  application_link: 'https://www.atedo.ch'
  extra_requirements_css:
    - atedo-branding/style/atedoCMS.css